### ISSUE TITLE
onscan.js `simulate` function doesn't work

### ISSUE THREAD

**Issue by agritheory** [agritheory/beam#1]
And it's not clear why. This is important for doing automated testing since you can't hook up a barcode scanner to a CI.

To reproduce, try the following in the browser console:
```js
window.scanHandler.scanner.simulate('3767127653309169910', document) // replace with a valid barcode or handling unit in your system
```

**Comment by Alchez** [comment]
@agritheory, the signature for the simulate function is actually `simulate(DOMElement, mStringOrArray)` and I was able to successfully get this to run:

```js
window.scanHandler.scanner.simulate(document, 'handling_unit_id')
```

**Comment by agritheory** [comment]
That's what I was doing wrong. Feels silly now.
