### ISSUE TITLE
Warehouse scanning not working in V15

### ISSUE THREAD

**Issue by agritheory** [agritheory/beam#100]
Confirmed on both Stock Entry - Material Receipt and Material Transfer as well as Purchase Receipt

To reproduce: use the `window.scanner.ScanHander.simulate` API on a warehouse in any listview or form view.

**Comment by fproldan** [comment]
@agritheory Am I following the correct steps to reproduce the problem? seems to work fine


[screencast-bpconcjcammlapcogcnnelfmaeghhagj-2024.04.03-14_15_36.webm](https://github.com/agritheory/beam/assets/4945122/1771a9ab-059e-41bc-b3e0-273ddfba2e57)

**Comment by agritheory** [comment]
@fproldan That's not what I meant but I can see how you read the bug report that way. With a barcode linked to a warehouse generated, try scanning that barcode in the warehouse list view.

Second test: set that warehouse as the default warehouse in Item Default and then scan the warehouse's barcode from the Item list view. 

I couldn't get either of those things to work when I was trying to demo this the other day. I didn't dig into it any further at that point.

**Comment by agritheory** [comment]
I tried again and couldn't reproduce this.
