### ISSUE TITLE
[Demand] Warehouse descendant lookup

### ISSUE THREAD

**Issue by agritheory** [agritheory/beam#107]
From #106: 
> Add nuance to the warehouse(s) signaling demand. This should be configurable and based on a multiselect of warehouse type and parent(s) so as to exclude quality/ quarantine warehouses, subcontractor warehouses and/or third-party warehousing solutions.

<br>

ERPNext has an imperfect implementation of this idea in the Auto Reorder abstraction. Its shortcoming include that it's not company sensitive (which can be an advantage, I suppose). One of the features that _is_ implemented is its ability to check in descendant warehouses. That said, not all warehouse types should be checked and I think it makes sense to require a configuration that one or more warehouses have a specific Warehouse Type(s) that allows the user to filter for the correct goods.

**Comment by MyuddinKhatri** [comment]
@agritheory Where should we configure the multiselect of warehouse types to include or exclude types of warehouses while getting the descendants of the warehouse, Can we add it Stock Settings? After we are ready with the API that gets descendants warehouse according to our filter where do we want to user/implement it in this feature(Demand)?

**Comment by agritheory** [comment]
@MyuddinKhatri We want to do this in BEAM Settings so its sensitive per-company. The demo data for this should be good enough to get started.

**Comment by MyuddinKhatri** [comment]
@agritheory Can this be marked as completed?
