### ISSUE TITLE
[demand] Wrap access to `demand.db` with ACID compliant file handler 

### ISSUE THREAD

**Issue by agritheory** [agritheory/beam#109]
It is likely that multiple workers or processes will want to access `demand.db` at the same time. Multiple reads should be fine, multiple write should not. Using an ACID compliant file handler like [ACID files](https://pypi.org/project/acidfile/) should be a reasonable solution to this that allows us to avoid a DBMS layer.

---

For discussion sake, I think it would be appropriate to mention network-friendly implementations of this idea.
- sqlite can be wrapped such that it is [accessible from HTTP](https://github.com/asg017/sqlite-http)
 - sqlite can also be wrapped with the postgres wire protocol but this [seems to have been deprecated ](https://turso.tech/blog/sqlite-based-databases-on-the-postgres-protocol-yes-we-can-358e61171d65)
 - It would also be possible with the ACID approach to use an NFS mount and share the file between know machines/ Frappe runtimes explicitly.
 - It would NOT be appropriate to expose it to a BI platform like Metabase or Frappe Insights, though it may be possible with limited replication techniques, though this defeats the real time intent of the data

**Comment by agritheory** [comment]
ACID Files does not seem to be maintained. Let's look at [Filelock](https://github.com/tox-dev/filelock) instead

**Comment by MyuddinKhatri** [comment]
> ACID Files does not seem to be maintained. Let's look at [Filelock](https://github.com/tox-dev/filelock) instead

@agritheory I think we can use this frappe has https://github.com/frappe/frappe/blob/develop/frappe/utils/synchronization.py#L18 this seems like a wrapper around filelock.

**Comment by agritheory** [comment]
@MyuddinKhatri Perfect, let's use that.
