### ISSUE TITLE
Evaluate history modes for Vue Router

### ISSUE THREAD

**Issue by Alchez** [agritheory/beam#138]
**Ref:** https://router.vuejs.org/guide/essentials/history-mode

---

**Hash mode:**
- The basic idea with this mode is that the URL always stays the same, and routes are automatically prefixed by the `#` symbol to indicate URL fragments.
  - Going from `/` to `/workstations` would essentially go from `https://beam.com/` to `https://beam.com/#workstations`.
- This works great for internal SPA applications that don't need to be indexed on the internet (and other SEO considerations).
- Since there's always a single entry-point to the app, additional routes (eg., 404 pages) don't need to be specially handled.
- Going back and forward in history is possible to perform programmatically.

**HTML5 mode:**
- This mode simulates normal browser routes and doesn't contain the `#` character like above.
  - Going from `/` to `/workstations` would just be going from `https://beam.com/` to `https://beam.com/workstations`.
- This works well for any kind of SPA application and allows for SEO indexing.
- Since any route combinations are possible, the app should handle a catch-all fallback to handle additional routes (eg., 404 pages).
- Going back and forward in history is possible to perform programmatically.

**Memory mode:**
- This mode is recommended for non-browser applications (Node.js and SSR), which means that it doesn't work with URLs at all.
- The history is internally tracked instead inside a "virtual" stack.
- Since the memory mode doesn't have access to the URL, an initial route must be set to the history stack.
- Going back and forward in history is not possible because of the above reasons.

---

Given the above, I think we should consider hash mode for ease of use (but only if all applications of the mobile view do not need to be indexed) and HTML5 mode if we want normal browser routes and SEO for the mobile view.

**Comment by agritheory** [comment]
@Alchez I think that hash mode makes the most sense. We don't need search indexing.

**Comment by Alchez** [comment]
Let's use hash mode for Beam mobile views
