### ISSUE TITLE
[mobile] Refactor scanning decision matrix to apply to list views in Mobile context

### ISSUE THREAD

**Issue by agritheory** [agritheory/beam#158]
We want to apply this programmatically so that overrides can be handled appropriately.

**Comment by agritheory** [comment]
Testing with the newly updated useScan composable, I don't see this updating anything in the Work Order view like `/beam#/work_order/MFG-WO-2024-00002`.  

I believe this is because we don't have the components wired up to the store yet, so let's close this one when we get most of that worked out.

**Comment by Alchez** [comment]
Required items should now increment by one with each scan, via #182.
