### ISSUE TITLE
[mobile] BEAM document / metadata component

### ISSUE THREAD

**Issue by agritheory** [agritheory/beam#161]
**Receive** context:
Supplier, linked Purchase Order(s)

Use ListView component to show items and the accepted and rejected qty, warehouse should be noted in the description

**Ship** context:
Customer, linked Sales Order(s)

Use ListView component to show items and the delivered qty, warehouse should be noted in the description

**Transfer** context:
Work Order, BOM No, Production Item, Total Qty

Use ListView component to show input items and the required qty, source warehouse should be noted in the description

**Comment by Alchez** [comment]
Dependent on https://github.com/agritheory/stonecrop/issues/145.

**Comment by agritheory** [comment]
@lauty95 Assigning this one to you

**Comment by lauty95** [comment]
@agritheory
I need to show some fields like Supplier and Customers and the actually endpoints just have this:

```JSON
{
      "key": "f4d0f1634244989ba2e080344021102ff3c0b54a3e013673c5637d49",
      "doctype": "Purchase Order",
      "company": "Ambrosia Pie Company",
      "parent": "PUR-ORD-2024-00001",
      "warehouse": "Refrigerator - APC",
      "name": "3nhjbjvaur",
      "idx": 1,
      "item_code": "Cloudberry",
      "schedule_date": "2024-01-01 00:00:00",
      "modified": "2024-11-07 09:37:23.016106",
      "stock_uom": "Pound",
      "stock_qty": 60.0,
      "received_qty": 0.0,
      "status": "",
      "assigned": null,
      "creation": "2024-11-07 09:36:13.961016"
}
```

The components are using these endpoints:
* https://github.com/agritheory/beam/blob/ba61eeabdc6aec9d8ee8867c85bdccdb9ced9da8/beam/beam/demand/receiving.py#L223

* https://github.com/agritheory/beam/blob/ba61eeabdc6aec9d8ee8867c85bdccdb9ced9da8/beam/beam/demand/demand.py#L678


I'd add `supplier` and `customer` in sqlyte.py https://github.com/agritheory/beam/blob/ba61eeabdc6aec9d8ee8867c85bdccdb9ced9da8/beam/beam/demand/sqlite.py#L89
when it creates receiving and demand tables.

Is it ok?

**Comment by agritheory** [comment]
@lauty95 For the receiving one, yes, we should be getting the supplier too. For the regular demand one, skip it. For the shipping demand, yes.
