### ISSUE TITLE
Setup github Codespace

### ISSUE THREAD

**Issue by agritheory** [agritheory/beam#177]
https://github.com/vjFaLk/frappe_codespace

**Comment by agritheory** [comment]
@hpema or @vjFaLk can assist

**Comment by hpema** [comment]
Hi Tyler,

Will attempt this using @vjFaLk repo and see if I can get one up and running

**Comment by hpema** [comment]
Managed to get a codespace running using: https://github.com/ankush/frappe_codespace.git

Will discuss further on your requirements when you online.

**Comment by vjFaLk** [comment]
@hpema Ah I was just gonna mention that my original version is probably outdated, glad you found a working fork.

**Comment by hpema** [comment]
> @hpema Ah I was just gonna mention that my original version is probably outdated, glad you found a working fork.

@vjFaLk - what would be nice if you could create a post on discuss forum or a tutorial to getting codespaces setup from scratch and adding erpnext and other apps etc. Are you able to do this?

@agritheory, Ive handing this over to @Alchez to investigate further and get our dev workflows added to using codespaces

**Comment by Alchez** [comment]
@agritheory Okay, I was able to fork ankush's repo and generate a bench inside a dev-container with the ERPNext and Beam apps installed (version-15 and mobile_v15 branches respectively). Can you confirm if the `/beam` UI looks fine?

URL - https://redesigned-space-halibut-q794645wp7v34p6-8000.app.github.dev/
User - `administrator`
Pass - `admin`

PS: I have 120 free codespace hours, so I'll keep this one up for a day max.

**Comment by agritheory** [comment]
Looks good!
@alchez, go ahead and take that down. Your proposal is to merge this with the base branch and then it can be used for `mobile_v15`?

**Comment by Alchez** [comment]
@agritheory I'm making some more changes that make it work for any branch. If that works, these changes could go to any branch.
