### ISSUE TITLE
Unable to run Beam on Codespace

### ISSUE THREAD

**Issue by crabinak** [agritheory/beam#197]
@agritheory I've been attempting to get Beam running in the Codespace. I can get 'bench start' to run, but I only receive 404 errors whenever I try to view in my browser. 

The beam/www folder also does not contain the beam/pages directory or any files. Is there an installation step I am missing? I tried to build the project per the readme instructions but it didn't make a difference. Let me know if I am missing something here.

![bench-start-terminal](https://github.com/user-attachments/assets/f84f39e4-c6d9-4fd3-bdb9-df5fba49af86)
![bench-404-01](https://github.com/user-attachments/assets/df779e4d-3a6a-4b94-ae00-c99f921c9b8b)
![bench-404-02](https://github.com/user-attachments/assets/b5dfabbf-07ad-4a34-841a-b09d329af291)

**Comment by agritheory** [comment]
@crabinak Try checking out the mobile_v15 branch and then running the build command from the readme. I am having a problem with the codespace also, but its different from this one.

**Comment by Alchez** [comment]
@crabinak Are you facing an issue while accessing the web-server as well? Cause it seems like that port should be visible. Does changing the port visibility manually from inside the codespace ([docs](https://docs.github.com/en/codespaces/developing-in-a-codespace/forwarding-ports-in-your-codespace#sharing-a-port)) allow you to access it?

@agritheory Let me know what errors you're facing as well, I'll probably end up doing another pass to expand the docs and/or the codespace setup.

**Comment by crabinak** [comment]
@Alchez Changing port visibility doesn't allow access for me. I am noticing that branch 'version-15' is the default checked out branch in the codespace even if I manually choose 'mobile_v15' as the checkout branch. When the codespace is running, there are no other branch options except for version-15, so I can't actually switch to any other branch.  Even 'git branch' only reports the single branch and won't recognize any branch switching. 

I'm unsure why the codespace is forcing me to use the version-15 branch but I'm guessing this might be the cause of my issue.
