### ISSUE TITLE
[mobile] compute dirty / unsaved state on record when item is scanned or entered

### ISSUE THREAD

**Issue by agritheory** [agritheory/beam#216]
TBD if changes should be cached or discarded when the user navigates away from the page

I propose that a hash of the values in object are stored (in the store) when it is fetched from the server and then a computed can reference that same value at any time later. I think this should get a larger design discussion when implemented in @stonecrop/stonecrop.

**Comment by Alchez** [comment]
@agritheory

There's a couple of strategies we may be able to use for this:
- We can use Pinia's' [`store.$subscribe`](https://pinia.vuejs.org/core-concepts/state.html#Subscribing-to-the-state) functionality to watch for changes to the store's state (we already do this in [one place](https://github.com/agritheory/beam/blob/ba61eeabdc6aec9d8ee8867c85bdccdb9ced9da8/beam/www/beam/components/Transfer.vue#L27) atleast).
  - This could be a good first iteration as is and may work in the majority of cases, but maybe there's an edge case where the original state is recreated after a series of mutations?
- We employ [object hashing](https://www.npmjs.com/package/object-hash) to the original state and then compare it with each subsequent state mutation to see if the form is "dirty". This could work with the subscribe function in tandem as well.

Is there a scenario where we'd need to compare states outside of Pinia stores for verifying the form's dirty status?

**Comment by agritheory** [comment]
> Is there a scenario where we'd need to compare states outside of Pinia stores for verifying the form's dirty status?

I don't think so. We need to surface to the user that there are unsaved changes.
