### ISSUE TITLE
Add Typing for scan APIs and functions

### ISSUE THREAD

**Issue by agritheory** [agritheory/beam#4]

**Comment by Alchez** [comment]
@agritheory, I've added typing to the scan functions in Python, but Frappe's pre-commit config is auto-converting something like `Optional[str]` to `str | None`. The pipe operator for typing was [introduced in py3.10](https://peps.python.org/pep-0604/), so this syntax will fail on anything less.

Let me know if you plan to support a version below 3.10, and I can force-commit changes using the `typing` module aliases.

**Comment by agritheory** [comment]
Let's change the pyupgrade pre-commit hook argument to 3.8 instead.

**Comment by Alchez** [comment]
Fixed with [`d62974d` (#3)](https://github.com/agritheory/beam/pull/3/commits/d62974df174df4aede2c7a03cf0e72391526c806).
