### ISSUE TITLE
Make Items opt-out for Handling Units

### ISSUE THREAD

**Issue by agritheory** [agritheory/beam#43]
Customization on the Item level that checks during Handling Unit creation if the item is opt-out (defaults to checked). Examples of this might be bulk materials (water, sand, corn silage) that are typically received without any kind of packing materials. I would name this field "Enable Handling Unit" checkbox

This could also theoretically be integrated into the design for #22.

**Comment by agritheory** [comment]
SAP's documentation on this topic: https://help.sap.com/docs/SAP_EXTENDED_WAREHOUSE_MANAGEMENT/3d97bec9bf1649099384bb8167df3cf2/570964b9-ac7f-4f33-8738-9e587238520e.html?version=9.5.0.0

**Comment by agritheory** [comment]
Additional consideration in a subcontracting workflow:
When items are send to a subcontractor, it's not always possible to preserve the Handling Unit or individual ID of an item. If parts are being completely consumed or if sub is responsible for a paint or finishing operation. Also, the sub may not care at all about the uniqueness of a HU. 

It makes sense to me to be able to optionally discard the Handling Unit when it is being sent to a subcontractor. When the item is received back, it can have a new Handling Unit assigned then. This breaks Handling Unit level traceability.

**Comment by viralkansodiya** [comment]
@agritheory During a subcontracting process, system is not creating Handling Unit when we receive the finished item, right?
not at the time of the subcontracting receipt and also not at the time of the purchase receipt of service item?

**Comment by viralkansodiya** [comment]
@agritheory 
Currently, the system is creating handling unit for all item,
do you want to change this process based on Enable Handling Unit check box which is available in Item Master ?

**Comment by agritheory** [comment]
@viralkansodiya Yes, if an item is tracked via handling unit, we want it to be created every time. This issue describes the scenario where an item should not be tracked with a handling unit

**Comment by viralkansodiya** [comment]
@agritheory 
after a deep testing of beam app, I observed some point which need improvement.

"The filter is not functioning properly in the 'handling_unit' field within the stock entry detail.

If an item is already available in the child table, then we need to check if there is a handling unit specified in the row. If not, we should input the handling unit number obtained via scanner.

I believe we need to implement a validation for Stock Entry Detail: if an item has handling unit enabled, then the handling unit field should be mandatory in the stock entry detail."

**Comment by viralkansodiya** [comment]
@agritheory 
I got the solution of this issue #43 
I will raise PR soon

**Comment by agritheory** [comment]
@viralkansodiya I think this is a good point, but it needs at least one tweak:
In a case of Material Receipt Stock Entry, it can't be required because it should be generated by BEAM at that time. I think in other cases it should be fine.
