### ISSUE TITLE
Change pre-process strategy

### ISSUE THREAD

**Issue by agritheory** [agritheory/beam#7]
It seems that the approach for fetching handling units' details is relatively complete. We need to expand the strategy for other Beam-enabled data types: Item, Asset and Warehouse

The Item's return value should be similar to what is done with ERPNext's `get_item_details` function. An asset would be similar but not enabled in all form inputs.

Warehouse might be the trickiest because we want actions with it to be smart:
For example in a Stock Entry:
- Scan Item (populates Stock Entry Detail row)
- Scan Warehouse (updates the warehouse is the row that was just added)

Or:
- Scan Warehouse (no rows; populates an Item if it is the only item in that warehouse, otherwise  it only populates the warehouse)

Additional design requirements will be added to this ticket and the project documentation over time

**Comment by Alchez** [comment]
@agritheory, here's a link for the differences between the `get_item_details` (left) and the handling unit (right) responses:

https://www.diffchecker.com/fbD78Wef/
