### ISSUE TITLE
Restructure decision matrix

### ISSUE THREAD

**Issue by agritheory** [agritheory/beam#9]
Instead of the confusing tuple-keyed dictionary, let's use another layer of nesting:
```python
"Item" : {
    "Purchase Receipt": [
	("add_or_increment", "Purchase Receipt Item", "item_code", target.item_code, target),
    ]
```

This will allow for clearer access of the correct function(s) and to make it hookable in the future.

**Comment by Alchez** [comment]
Fixed in [`44e15df` (#3)](https://github.com/agritheory/beam/pull/3/commits/44e15dfb2c2ca1086637c8429846f4bb47706a01)
