### ISSUE TITLE
Display Quantity Columns in Recombination Pop-up Window on Cancellation of Stock Entry (Material Transfer Type)

### ISSUE THREAD

**Issue by basawaraj-fosserp** [agritheory/beam#91]
Currently when a Stock Entry (Material Transfer type) is cancelled, a pop-up appears which allows users to select items for which the handling units must be re-combined.

The pop-up window has only three columns: Item Code, Handling Unit, Handling Unit to recombine.

Add additional columns displaying the quantities of each handling units.

The sequence of column should be Item Code, Handling Unit, Quantity, Handling Unit to recombine, Quantity.

![Screenshot 2024-03-08 at 12 00 35 PM](https://github.com/agritheory/beam/assets/103717083/ae6ec027-04d0-4a22-a108-a7171792787b)

**Comment by viralkansodiya** [comment]
@basawaraj-fosserp 
Please review this PR #93
